# ==============================================================================
# Jekyll Configuration
# https://jekyllrb.com/docs/configuration/default/
# ==============================================================================
# Where things are
collections_dir: docs
collections:
  education:
    output: true
  project:
    output: true

# Handling Reading
strict_front_matter: false

# Filtering Content
show_drafts: false
future: true
unpublished: false

# Outputting
timezone: Asia/Seoul
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Markdown Processors
kramdown:
  show_warnings: true
  math_engine: mathjax

# ==============================================================================
# Theme Configuration
# ==============================================================================
