name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  workflow_call:
    secrets:
      PRIVATE_REPO_ACCESS_TOKEN:
        # https://github.com/Hepheir/hepheir.github.io/settings/secrets/actions
        # Add a secret named "PRIVATE_REPO_ACCESS_TOKEN" on the link above.
        description: 'A Personal Access Token which can access to private repositories'
        required: true

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          fetch-depth: 0  # for posts's lastmod
          submodules: true

      - name: Update submodule
        run: |
          git submodule update --remote

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Deploy
        run: bash tools/deploy.sh
